# Generated by Django 4.2 on 2025-06-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "course_chapter",
            },
        ),
        migrations.CreateModel(
            name="ChapterLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chapter.chapter",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
                    ),
                ),
            ],
            options={
                "db_table": "chapter_lesson_mapping",
                "ordering": ["order"],
                "unique_together": {("chapter", "lesson")},
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="lessons",
            field=models.ManyToManyField(
                related_name="lessons",
                through="chapter.ChapterLesson",
                to="lesson.lesson",
            ),
        ),
        migrations.CreateModel(
            name="ChapterTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="chapter.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chapter translations",
                "db_table": "course_chapter_translation",
                "unique_together": {("chapter", "language")},
            },
        ),
    ]
