FROM python:3.9-slim

# set work directory
WORKDIR /usr/src/app/backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependencies and Postgres 16 client
# Update package lists
RUN apt-get update

# Install general dependencies
RUN apt-get install -y \
    wget \
    gnupg2 \
    lsb-release \
    curl \
    gcc \
    libcairo2 \
    libcairo2-dev \
    libpangocairo-1.0-0 \
    gettext \
    cron

# Add PostgreSQL repository
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
    > /etc/apt/sources.list.d/pgdg.list

# Add PostgreSQL GPG key
RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
    | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

# Update package lists again for PostgreSQL repo
RUN apt-get update

# Install PostgreSQL client 16 and development libraries
RUN apt-get install -y \
    postgresql-client-16 \
    libpq-dev

# Install Python PostgreSQL adapter
RUN pip install psycopg2

# Clean up to reduce image size
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install django-cors-headers

# copy project
COPY . .

EXPOSE 8000

# run main.sh
RUN ["chmod", "+x",  "./main.sh"]
ENTRYPOINT ["./main.sh"]