# Generated by Django 4.2 on 2025-06-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("instructor_user", "0001_initial"),
        ("level", "0001_initial"),
        ("technology", "0001_initial"),
        ("category", "0001_initial"),
        ("chapter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
                ("duration", models.PositiveIntegerField()),
                ("chat_url", models.URLField()),
                ("active", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="category.category",
                    ),
                ),
            ],
            options={
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="CourseChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chapter.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
            options={
                "db_table": "course_chapter_mapping",
                "ordering": ["order"],
                "unique_together": {("course", "chapter")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="chapters",
            field=models.ManyToManyField(
                related_name="courses",
                through="course.CourseChapter",
                to="chapter.chapter",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="courses", to="instructor_user.instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="level.level"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="dependent_courses", to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="technology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="technology.technology"
            ),
        ),
        migrations.CreateModel(
            name="CourseTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("overview", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course translations",
                "db_table": "course_translation",
                "unique_together": {("course", "language")},
            },
        ),
    ]
