# Generated by Django 4.2 on 2025-08-21 08:51

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import project.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("project_tag", "0001_initial"),
        ("level", "0001_initial"),
        ("blog", "0001_initial"),
        ("technology", "0001_initial"),
        ("stage", "0001_initial"),
        ("instructor_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "video_url",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=project.models.project_directory_path,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "blog_prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="dependent_blogs", to="blog.blog"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="category.category",
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        related_name="projects", to="instructor_user.instructor"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="level.level"
                    ),
                ),
                (
                    "project_prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_projects",
                        to="project.project",
                    ),
                ),
                (
                    "similar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="similar_projects",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stage.stage"
                    ),
                ),
            ],
            options={
                "db_table": "project_stage_mapping",
                "ordering": ["order"],
                "unique_together": {("project", "stage")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="stages",
            field=models.ManyToManyField(
                related_name="projects",
                through="project.ProjectStage",
                to="stage.stage",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(related_name="projects", to="project_tag.tag"),
        ),
        migrations.AddField(
            model_name="project",
            name="technology",
            field=models.ManyToManyField(
                db_table="project_to_technology",
                related_name="projects",
                to="technology.technology",
            ),
        ),
        migrations.CreateModel(
            name="ProjectTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("overview", mdeditor.fields.MDTextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project translations",
                "db_table": "project_translation",
                "unique_together": {("project", "language")},
            },
        ),
    ]
