# Generated by Django 4.2 on 2025-07-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('step', '0001_initial'),
        ('category', '0001_initial'),
        ('instructor_user', '0001_initial'),
        ('level', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('chat_url', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('instructors', models.ManyToManyField(related_name='projects', to='instructor_user.instructor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='level.level')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_projects', to='project.project')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.step')),
            ],
            options={
                'db_table': 'project_step_mapping',
                'ordering': ['order'],
                'unique_together': {('project', 'step')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='steps',
            field=models.ManyToManyField(related_name='projects', through='project.ProjectStep', to='step.step'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(db_table='project_to_technology', related_name='projects', to='technology.technology'),
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project translations',
                'db_table': 'project_translation',
                'unique_together': {('project', 'language')},
            },
        ),
    ]
