# Generated by Django 4.2 on 2025-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_create_plans"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plans",
            field=models.ManyToManyField(related_name="projects", to="plan.plan"),
        ),
    ]
