# Generated by Django 4.2 on 2025-07-23 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="duration",
        ),
    ]
