# Generated by Django 4.2 on 2025-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prerequisites',
            new_name='project_prerequisites',
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
