# Generated by Django 4.2 on 2025-08-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_tag", "0001_initial"),
        ("project", "0002_alter_projecttranslation_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(related_name="projects", to="project_tag.tag"),
        ),
    ]
