# Generated by Django 4.2 on 2025-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('project', '0002_rename_prerequisites_project_project_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blog_prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_blogs', to='blog.blog'),
        ),
    ]
