# Generated by Django 4.2 on 2025-08-14 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="chat_url",
        ),
    ]
