# Generated by Django 4.2 on 2025-07-16 17:29

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_blog_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=project.models.project_directory_path),
        ),
    ]
