# Generated by Django 4.2 on 2025-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='similar_projects', to='project.project'),
        ),
    ]
