# Generated by Django 4.2 on 2025-07-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('step', '0001_initial'),
        ('student_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.step')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_user.student')),
            ],
            options={
                'db_table': 'project_progress',
                'unique_together': {('student', 'step')},
            },
        ),
    ]
