# Generated by Django 4.2 on 2025-10-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Project tags",
                "db_table": "project_tag",
            },
        ),
        migrations.CreateModel(
            name="TagTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("name", models.CharField()),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="project_tag.tag",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project tag translations",
                "db_table": "project_tag_translation",
            },
        ),
        migrations.AddIndex(
            model_name="tagtranslation",
            index=models.Index(
                fields=["language"], name="project_tag_languag_708b42_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tagtranslation",
            unique_together={("tag", "language")},
        ),
    ]
