# Generated by Django 4.2 on 2025-10-06 18:55

from django.db import migrations, models
import project.consultation.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField()),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("requested", "Requested"),
                        ],
                        default="requested",
                        max_length=9,
                    ),
                ),
                ("join_link", models.URLField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=project.consultation.models.consultation_directory_path,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Consultations",
                "db_table": "consultation",
            },
        ),
    ]
