# Generated by Django 4.2 on 2025-10-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consultation", "0001_initial"),
        ("student_user", "0002_student_first_purchase"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="student_user.student",
            ),
        ),
    ]
