# Generated by Django 4.2 on 2025-07-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Substeps',
                'db_table': 'project_substep',
            },
        ),
        migrations.CreateModel(
            name='SubstepTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('substep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='substep.substep')),
            ],
            options={
                'verbose_name_plural': 'Substep translations',
                'db_table': 'project_substep_translation',
            },
        ),
    ]
