# Generated by Django 4.2 on 2025-08-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student_user", "0002_student_stripe_customer_id"),
        ("plan", "0002_create_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "plan_pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plan.planpricing",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
