# Generated by Django 4.2 on 2025-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_plansubscription_amount_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansubscription",
            name="stripe_promotion_code_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
