# Generated by Django 4.2 on 2025-07-24 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_plansubscription_currency_plansubscription_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plansubscription",
            name="price",
        ),
    ]
