# Generated by Django 4.2 on 2025-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0003_plansubscription_stripe_promotion_code_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansubscription",
            name="stripe_subscription_item_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
