# Generated by Django 4.2 on 2025-09-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_create_dummy_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
