# Generated by Django 4.2 on 2025-08-01 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_tokenusage"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tokenusage",
            table="token_usage",
        ),
    ]
