# Generated by Django 4.2 on 2025-08-01 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_tokenusage_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TokenUsage",
        ),
    ]
