export const URLS = {
  // AUTH
  REGISTER: "/auth/register",
  ACTIVATE: "/auth/activate",
  RESEND: "/auth/resend",
  LOGIN: "/auth/login",
  LOGIN_FACEBOOK: "/auth/facebook-login",
  LOGIN_GOOGLE: "/auth/google-login",
  LOGIN_GITHUB: "/auth/github-login",
  LOGOUT: "/auth/logout",
  PASSWORD_RESET: "/auth/reset-password",
  PASSWORD_UPDATE: "/auth/reset-password-confirm",
  REFRESH_TOKEN: "/auth/refresh-token",
  ACCESS_TOKEN: "/auth/access-token",
  // CONTACT
  CONTACT: "/contact",
  // COURSE
  COURSES: "/courses",
  COURSE_CATEGORIES: "/course-categories",
  COURSE_LEVELS: "/course-levels",
  COURSE_TECHNOLOGIES: "/course-technologies",
  SIMILAR_COURSES: "/similar-courses",
  // LESSON
  LESSON: "/lesson",
  LESSON_PROGRESS: "/lesson/progress",
  LESSON_SUBMIT: "/lesson/submit",
  LESSON_ANSWER: "/lesson/answer",
  LESSON_HINT: "/lesson/hint",
  // REVIEWS
  REVIEWS: "/reviews",
  REVIEWS_SUMMARY: "/reviews-summary",
  REVIEW_SUBMIT: "/review-submit",
  // BLOG
  POST_TOPICS: "/post-topics",
  POST_TAGS: "/post-tags",
  POSTS: "/posts",
  RECENT_POSTS: "/recent-posts",
  // FEATURED
  FEATURED_TECHNOLOGIES: "/featured-technologies",
  FEATURED_COURSES: "/featured-courses",
  FEATURED_REVIEWS: "/featured-reviews",
  FEATURED_POST: "/featured-post",
  // PLAN
  PLANS: "/plans",
  SUBSCRIBE: "/subscribe",
  // CERTIFICATES
  CERTIFICATES: "/certificates",
  // ME
  DATA: "/me/data",
  PASSWORD_CHANGE: "/me/password",
  DELETE_ACCOUNT: "/me/delete",
  DASHBOARD: "/me/dashboard",
} as const;
