# Generated by Django 4.2 on 2025-08-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "db_table": "option",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("popular", models.BooleanField(default=False)),
                ("premium", models.BooleanField(default=False)),
                ("tokens_limit", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "plan",
            },
        ),
        migrations.CreateModel(
            name="PlanTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("license", models.CharField(max_length=100)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("yearly_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PLN", "Pln"),
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                        ],
                        default="PLN",
                        max_length=3,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="plan.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_translation",
                "unique_together": {("plan", "language")},
            },
        ),
        migrations.CreateModel(
            name="PlanOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_options",
                        to="plan.option",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_options",
                        to="plan.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_option",
                "ordering": ["order"],
                "unique_together": {("plan", "option")},
            },
        ),
        migrations.CreateModel(
            name="OptionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="plan.option",
                    ),
                ),
            ],
            options={
                "db_table": "option_translation",
                "unique_together": {("option", "language")},
            },
        ),
    ]
