# Generated by Django 4.2 on 2025-10-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "db_table": "option",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                        ],
                        max_length=10,
                    ),
                ),
                ("popular", models.BooleanField(default=False)),
                ("tokens_limit", models.PositiveIntegerField(default=0)),
                ("consultation_limit", models.PositiveIntegerField(default=0)),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "plan",
            },
        ),
        migrations.CreateModel(
            name="PlanTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("license", models.CharField(max_length=100)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="plan.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_translation",
            },
        ),
        migrations.CreateModel(
            name="PlanPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PLN", "Pln"),
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                        ],
                        default="PLN",
                        max_length=3,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("valid_from", models.DateTimeField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricings",
                        to="plan.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_pricing",
            },
        ),
        migrations.CreateModel(
            name="PlanOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("disabled", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_options",
                        to="plan.option",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_options",
                        to="plan.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_option",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="OptionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="plan.option",
                    ),
                ),
            ],
            options={
                "db_table": "option_translation",
            },
        ),
        migrations.AddIndex(
            model_name="plantranslation",
            index=models.Index(
                fields=["language"], name="plan_transl_languag_8a00c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantranslation",
            unique_together={("plan", "language")},
        ),
        migrations.AddIndex(
            model_name="planpricing",
            index=models.Index(
                fields=["stripe_price_id"], name="plan_pricin_stripe__27e161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planpricing",
            index=models.Index(
                fields=["plan", "currency", "interval", "-valid_from"],
                name="plan_pricin_plan_id_14ff1d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planpricing",
            unique_together={("plan", "currency", "interval", "valid_from")},
        ),
        migrations.AddIndex(
            model_name="planoption",
            index=models.Index(
                fields=["plan", "order"], name="plan_option_plan_id_4ab4ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planoption",
            index=models.Index(fields=["order"], name="plan_option_order_a81a46_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="planoption",
            unique_together={("plan", "option")},
        ),
        migrations.AddIndex(
            model_name="optiontranslation",
            index=models.Index(
                fields=["language"], name="option_tran_languag_1abebc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="optiontranslation",
            unique_together={("option", "language")},
        ),
    ]
