# Generated by Django 4.2 on 2025-10-07 10:14


from django.db import migrations
from django.utils import timezone
from plan.models import Plan, PlanTranslation, PlanPricing
from const import PlanType, Language, Currency, PaymentInterval


def generate_plan(apps, schema_editor):
    for type in PlanType:
        plan = Plan.objects.create(type=type)
        for language in Language:
            PlanTranslation.objects.create(
                plan=plan,
                language=language,
                license="",
            )

        for currency in Currency:
            for interval in PaymentInterval:
                PlanPricing.objects.create(
                    plan=plan,
                    currency=currency,
                    interval=interval,
                    price=0,
                    valid_from=timezone.now(),
                )


def delete_plan(apps, schema_editor):
    plan_types = [pt[0] for pt in PlanType.choices]
    Plan.objects.filter(type__in=plan_types).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_plan, reverse_code=delete_plan)]
