# Generated by Django 4.2 on 2025-06-12 10:30

from django.db import migrations
from global_config import CONFIG
from plan.models import Plan


def generate_plan(apps, schema_editor):
    slug = CONFIG["default_plan"]

    if not Plan.objects.filter(slug=slug).exists():
        Plan.objects.create(slug=slug, monthly_price=0, yearly_price=0)


def delete_plan(apps, schema_editor):
    slug = CONFIG["default_plan"]

    try:
        plan = Plan.objects.get(slug=slug)
        plan.delete()
    except Plan.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_plan, reverse_code=delete_plan)]
