# Generated by Django 4.2 on 2025-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_create_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="consultation_limit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
