# Generated by Django 4.2 on 2025-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_create_default_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoption',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='planoption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
