# Generated by Django 4.2 on 2025-08-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_create_default_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantranslation",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="plantranslation",
            name="monthly_price",
        ),
        migrations.RemoveField(
            model_name="plantranslation",
            name="yearly_price",
        ),
        migrations.CreateModel(
            name="PlanPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PLN", "Pln"),
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                        ],
                        default="PLN",
                        max_length=3,
                    ),
                ),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("yearly_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricings",
                        to="plan.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_pricing",
                "unique_together": {("plan", "currency")},
            },
        ),
    ]
