# Generated by Django 4.2 on 2025-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_alter_planoption_options_planoption_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="tokens_limit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
