# Generated by Django 4.2 on 2025-08-08 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_remove_plantranslation_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planpricing",
            old_name="monthly_price",
            new_name="monthly",
        ),
        migrations.RenameField(
            model_name="planpricing",
            old_name="yearly_price",
            new_name="yearly",
        ),
    ]
