# Generated by Django 4.2 on 2025-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_planoption_options_planoption_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantranslation',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Pln'), ('EUR', 'Eur'), ('USD', 'Usd'), ('GBP', 'Gbp')], default='PLN', max_length=3),
        ),
    ]
