# Generated by Django 4.2 on 2025-07-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_stage',
            },
        ),
        migrations.CreateModel(
            name='StageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.stage')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.step')),
            ],
            options={
                'db_table': 'stage_step_mapping',
                'ordering': ['order'],
                'unique_together': {('stage', 'step')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='steps',
            field=models.ManyToManyField(related_name='steps', through='stage.StageStep', to='step.step'),
        ),
        migrations.CreateModel(
            name='StageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='stage.stage')),
            ],
            options={
                'verbose_name_plural': 'Stage translations',
                'db_table': 'project_stage_translation',
                'unique_together': {('stage', 'language')},
            },
        ),
    ]
