# Generated by Django 4.2 on 2025-07-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_step',
            },
        ),
        migrations.CreateModel(
            name='StepSubstep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.step')),
                ('substep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substep.substep')),
            ],
            options={
                'db_table': 'step_substep_mapping',
                'ordering': ['order'],
                'unique_together': {('step', 'substep')},
            },
        ),
        migrations.AddField(
            model_name='step',
            name='substeps',
            field=models.ManyToManyField(related_name='substeps', through='step.StepSubstep', to='substep.substep'),
        ),
        migrations.CreateModel(
            name='StepTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='step.step')),
            ],
            options={
                'verbose_name_plural': 'Step translations',
                'db_table': 'project_step_translation',
                'unique_together': {('step', 'language')},
            },
        ),
    ]
