# Generated by Django 4.2 on 2025-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='duration',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
