# Generated by Django 4.2 on 2025-10-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student_user", "0002_student_first_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("stripe_promotion_code_id", models.CharField(max_length=100)),
                ("stripe_coupon_id", models.CharField(max_length=100)),
                (
                    "percent_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "amount_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLN", "Pln"),
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_redemptions", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("restrictions", models.JSONField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("repeating", "Repeating"),
                            ("forever", "Forever"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("duration_in_months", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment Discount",
                "verbose_name_plural": "Payment Discounts",
                "db_table": "payment_discount",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_payment_method_id",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("paypal", "Paypal"),
                            ("revolut_pay", "Revolut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_method",
            },
        ),
        migrations.CreateModel(
            name="RevolutPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revolut",
                        to="payment.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "RevolutPay Payment Method",
                "verbose_name_plural": "RevolutPay Payment Methods",
                "db_table": "payment_method_revolutpay",
            },
        ),
        migrations.CreateModel(
            name="PayPalPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payer_email", models.EmailField(max_length=254, null=True)),
                (
                    "payment_method",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal",
                        to="payment.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Payment Method",
                "verbose_name_plural": "PayPal Payment Methods",
                "db_table": "payment_method_paypal",
            },
        ),
        migrations.CreateModel(
            name="CardPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("brand", models.CharField(max_length=50)),
                ("display_brand", models.CharField(max_length=50)),
                ("last4", models.CharField(max_length=4)),
                ("exp_month", models.PositiveIntegerField()),
                ("exp_year", models.PositiveIntegerField()),
                ("holder", models.CharField(max_length=50, null=True)),
                (
                    "wallet",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to="payment.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Payment Method",
                "verbose_name_plural": "Card Payment Methods",
                "db_table": "payment_method_card",
            },
        ),
    ]
