# Generated by Django 4.2 on 2025-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("stripe_promotion_code_id", models.CharField(max_length=100)),
                ("stripe_coupon_id", models.CharField(max_length=100)),
                (
                    "percent_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "amount_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_redemptions", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("restrictions", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment Discount",
                "verbose_name_plural": "Payment Discounts",
                "db_table": "payment_discount",
            },
        ),
    ]
