# Generated by Django 4.2 on 2025-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_paymentdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscount",
            name="duration",
            field=models.CharField(
                choices=[
                    ("once", "Once"),
                    ("repeating", "Repeating"),
                    ("forever", "Forever"),
                ],
                default="once",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentdiscount",
            name="duration_in_months",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
