# Generated by Django 4.2 on 2025-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_paymentdiscount_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscount",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLN", "Pln"),
                    ("EUR", "Eur"),
                    ("USD", "Usd"),
                    ("GBP", "Gbp"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
