# Generated by Django 4.2 on 2025-08-05 07:51

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogtranslation",
            name="content",
            field=mdeditor.fields.MDTextField(),
        ),
    ]
