# Generated by Django 4.2 on 2025-08-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
