# Generated by Django 4.2 on 2025-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_purchase",
            field=models.BooleanField(default=True),
        ),
    ]
