# Generated by Django 4.2 on 2025-10-07 10:15

from django.db import migrations, models
import django.db.models.deletion
import project.enrollment.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enrollment", "0001_initial"),
        ("student_user", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectenrollment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="projectenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=models.SET(project.enrollment.models.get_dummy_student),
                related_name="enrollments",
                to="student_user.student",
            ),
        ),
        migrations.AddIndex(
            model_name="projectenrollment",
            index=models.Index(
                fields=["student", "-created_at"], name="project_enr_student_036cff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectenrollment",
            unique_together={("student", "project")},
        ),
    ]
