# Generated by Django 4.2 on 2025-06-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
        ("student_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("answer", models.JSONField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("hint_used", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_progress",
                "unique_together": {("student", "lesson")},
            },
        ),
    ]
