# Generated by Django 4.2 on 2025-10-06 18:55

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import project.channel.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student_user", "0002_student_first_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "En"), ("pl", "Pl")], max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", mdeditor.fields.MDTextField()),
            ],
            options={
                "verbose_name_plural": "Channel posts",
                "db_table": "channel_post",
            },
        ),
        migrations.CreateModel(
            name="ChannelPostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="channel.channelpost",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_posts",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Channel post likes",
                "db_table": "channel_post_like",
            },
        ),
        migrations.CreateModel(
            name="ChannelPostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to=project.channel.models.image_directory_path,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Channel post images",
                "db_table": "channel_post_image",
            },
        ),
        migrations.CreateModel(
            name="ChannelPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", mdeditor.fields.MDTextField()),
                (
                    "channel_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="channel.channelpost",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Channel post comments",
                "db_table": "channel_post_comment",
            },
        ),
    ]
