# Generated by Django 4.2 on 2025-10-03 19:51

from django.db import migrations, models
import django.db.models.deletion
import project.channel.models


class Migration(migrations.Migration):
    dependencies = [
        ("student_user", "0001_initial"),
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelPostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to=project.channel.models.image_directory_path,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Channel post images",
                "db_table": "channel_post_image",
            },
        ),
    ]
