# Generated by Django 4.2 on 2025-10-07 10:15

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student_user", "0001_initial"),
        ("channel", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelpost",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_posts",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="channelpost",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_posts",
                to="student_user.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelpostlike",
            unique_together={("channel_post", "student")},
        ),
        migrations.AddIndex(
            model_name="channelpostcomment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["message"], name="cpc_message_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="channelpost",
            index=models.Index(
                fields=["project", "-created_at"], name="channel_pos_project_fcaaee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelpost",
            index=models.Index(
                fields=["student"], name="channel_pos_student_c9620b_idx"
            ),
        ),
    ]
