# Generated by Django 4.2 on 2025-08-05 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "Blog tags"},
        ),
        migrations.AlterModelOptions(
            name="tagtranslation",
            options={"verbose_name_plural": "Blog tag translations"},
        ),
    ]
